# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_car', models.BooleanField()),
                ('correct', models.BooleanField()),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
